packages:
  - apps/*
  - packages/*
  - video

onlyBuiltDependencies:
  - '@google/genai'
  - electron
  - electron-winstaller
  - esbuild
  - koffi
  - node-pty
  - protobufjs
  - sharp

supportedArchitectures:
  os:
    - current
    - win32
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
